import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";

const global_font = Exo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={global_font.className}>{children}</body>
    </html>
  );
}
