import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import CustomCursor from "./components/customCursor";
import FloatingChatButton from "./components/floatingChatButton";

const global_font = Exo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={global_font.className}>
        <CustomCursor />
        <main className="flex justify-center">
          <div className="2xl:max-w-[1450px] flex flex-col items-center">
            {children}
          </div>
        </main>
        <FloatingChatButton />
      </body>
    </html>
  );
}
